owner: pillexa-dev
repo: medmosa-status

sites:
  - name: Medmosa Production
    url: https://medmosa.com
  - name: Medmosa Staging
    url: https://staging.medmosa.com

status-website:
  publish: true
  baseUrl: /
  cname: status.medmosa.com
  logoUrl: https://medmosa.com/favicon.ico
  name: Medmosa Status
  introTitle: "**Medmosa** System Status"
  introMessage: Real-time status of Medmosa services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - PrinceMahdi
