owner: pillexa-dev
repo: medmosa-status

sites:
  - name: Medmosa Production
    url: https://medmosa.com
  - name: Medmosa Staging
    url: https://staging.medmosa.com

status-website:
  publish: true
  cname: status.medmosa.com
  logoUrl: https://medmosa.com/favicon.ico
  name: Medmosa Status
  introTitle: "**Medmosa** System Status"
  introMessage: Real-time status of Medmosa services.
  navbar:
    - title: Status
      href: /
  customHeadHtml: "<style>footer, .github-link, a[href*='github.com'][class*='btn'], .btn-github, article a[href*='github'], .subscribe-link { display: none !important; }</style>"

assignees:
  - PrinceMahdi
